spring:
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  application:
    name: Bookmarker
info:
  app:
    name: Bookmarker
    description: BookMarker REST API
    version: @project.version@
  contact:
    name: bobo
    email: bobo@spring2go.com
    url: https://spring2go.com
logging:
  level:
    com.spring2go: debug
jasypt:
  encryptor:
    password: dummy
bookmarker:
  jwt:
    issuer: BookMarker
    header: Authorization
    secret: ENC(qMZ/E1jhRSmmNnUhB9mOdw==)
    expires-in: 604800